### ISSUE TITLE
TypeError: download_raw() got an unexpected keyword argument 'project_name'

### ISSUE THREAD

**Issue by Xinzhao1990** [MetaSUB/metasub_utils#9]
* MetaSUB Utilities version: v0.5.3
* Python version:3.6
* Operating System:macOS 10.14.1

### What I Did

Hi David,

I installed metasub_utils (v0.5.3) and tried to download data using --project-name flag and --sample-names flag. However, I received error saying 

> TypeError: download_raw() got an unexpected keyword argument 'project_name'

I have a copy of metadata [MetaSub_Complete_CSD16_17_with_HudsonAlpha_ID_v1.1.xlsx](https://github.com/MetaSUB/metasub_utils/files/2745457/MetaSub_Complete_CSD16_17_with_HudsonAlpha_ID_v1.1.xlsx), and I assume that the project names are those under`HA_project` column such as haib18CEM5332 and sample names are those under `sample_ID` such as 235039335, right? I just want to make sure everything is alright (I highlighted the columns names of attached spreadsheet), please correct me if I am wrong. 
```
Paste the command(s) you ran and the output.

# City name and project name are specified 
XinzhaodeMacBook-Pro:surface_data Xinzhao$ metasub wasabi download-raw-reads --city-name hong_kong --wetrun --project-name haib18CEM5332
Traceback (most recent call last):
  File "/Users/xinzhao/miniconda3/bin/metasub", line 11, in <module>
    sys.exit(main())
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/metasub_utils/wasabi/cli.py", line 99, in cli_download_raw_data
    dryrun=dryrun,
TypeError: download_raw() got an unexpected keyword argument 'project_name'
XinzhaodeMacBook-Pro:surface_data Xinzhao$ metasub wasabi download-raw-reads --wetrun --city-name oslo
Traceback (most recent call last):
  File "/Users/xinzhao/miniconda3/bin/metasub", line 11, in <module>
    sys.exit(main())
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/metasub_utils/wasabi/cli.py", line 99, in cli_download_raw_data
    dryrun=dryrun,
TypeError: download_raw() got an unexpected keyword argument 'project_name'

# City name and sample name are specified 
XinzhaodeMacBook-Pro:surface_data Xinzhao$ metasub wasabi download-raw-reads --wetrun --city-name hong_kong --sample-names 235039335
Usage: metasub wasabi download-raw-reads [OPTIONS] [TARGET_DIR]
Try "metasub wasabi download-raw-reads --help" for help.

Error: Invalid value for "-n" / "--sample-names": Could not open file: 235039335: No such file or directory

Thank you again for your time and help

**Comment by dcdanko** [comment]
🤦‍♂️ my bad.

Fixed with PR #10 and `v0.5.5`

**Comment by Xinzhao1990** [comment]
After updating to v0.5.5, I received another error...

```

XinzhaodeMacBook-Pro:metasub_surface Xinzhao$ metasub wasabi download-raw-reads --wetrun --city-name hong_kong --project-name haib18CEM5453
Traceback (most recent call last):
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/httpsession.py", line 258, in send
    decode_content=False,
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x117fe7550>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinzhao/miniconda3/bin/metasub", line 11, in <module>
    sys.exit(main())
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/metasub_utils/wasabi/cli.py", line 104, in cli_download_raw_data
    dryrun=dryrun,
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/metasub_utils/wasabi/wasabi_bucket.py", line 100, in download_raw
    read_files = self.list_raw(city_name=city_name, project_name=project_name, sample_names=sample_names)
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/metasub_utils/wasabi/wasabi_bucket.py", line 79, in list_raw
    for key in self.bucket.objects.filter(Prefix='data')
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/metasub_utils/wasabi/wasabi_bucket.py", line 77, in <setcomp>
    raw_reads = {
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/Users/xinzhao/miniconda3/lib/python3.6/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/Users/xinzhao/.local/lib/python3.6/site-packages/botocore/httpsession.py", line 278, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.wasabisys.com/metasub?prefix=data&encoding-type=url"

```

Thank again for you help

**Comment by dcdanko** [comment]
Have you configured your Wasabi-S3 credentials? It looks like you haven't.

**Comment by Xinzhao1990** [comment]
Sorry, my fault.

I tried to download data using the code below
XinzhaodeMacBook-Pro:metasub_surface Xinzhao$ metasub wasabi download-raw-reads --city-name hong_kong --project-name CSD17
WASABI DOWNLOADING data/hudson_alpha_library/haib18CEM5453/HNHKFCCXY/haib18CEM5453_HNHKFCCXY_SL345497_1.fastq.gz data/hudson_alpha_library/haib18CEM5453/HNHKFCCXY/haib18CEM5453_HNHKFCCXY_SL345497_1.fastq.gz
WASABI DOWNLOADING data/hudson_alpha_library/haib18CEM5453/HNHKFCCXY/haib18CEM5453_HNHKFCCXY_SL345497_2.fastq.gz data/hudson_alpha_library/haib18CEM5453/HNHKFCCXY/haib18CEM5453_HNHKFCCXY_SL345497_2.fastq.gz
WASABI DOWNLOADING data/hudson_alpha_library/haib18CEM5453/HMC2KCCXY/haib18CEM5453_HMC2KCCXY_SL336681_1.fastq.gz data/hudson_alpha_library/haib18CEM5453/HMC2KCCXY/haib18CEM5453_HMC2KCCXY_SL336681_1.fastq.gz
WASABI DOWNLOADING data/hudson_alpha_library/haib18CEM5453/HMC2KCCXY/haib18CEM5453_HMC2KCCXY_SL336681_2.fastq.gz data/hudson_alpha_library/haib18CEM5453/HMC2KCCXY/haib18CEM5453_HMC2KCCXY_SL336681_2.fastq.gz

It seems that paired end reads could be downloaded consecutively if I specify the project name with "CSD17". However, I have no idea about the sample names, and I am keep receiving error. Obviously, the same names I specify here is not correct.

XinzhaodeMacBook-Pro:metasub_surface Xinzhao$ metasub wasabi download-raw-reads --city-name hong_kong --sample-names SL310968

Error: Invalid value for "-n" / "--sample-names": Could not open file: SL310968: No such file or directory
Error: Invalid value for "-n" / "--sample-names": Could not open file: gCSD17-HKG-AS1: No such file or directory

Could you please send me a copy of the metadata you are using (my email: xinzhtong2-c@my.cityu.edu.hk), and it would be great if you could highlight the columns of sample names and project names which we should specify here. 

Thank you very much.

**Comment by dcdanko** [comment]
You can find the metadata [here](https://github.com/MetaSUB/MetaSUB-metadata/blob/master/complete_metadata.csv). But there is actually a utility to do exactly what you need.

`--sample-names` expects a file with a list of samples names. In your case run the following

```
metasub metadata samples-from-city hong_kong > all_hong_kong_sample_names.txt
split -l 100 all_hong_kong_sample_names.txt chunk chunk_
for f in chunk_*; do echo $f; metasub wasabi download-raw-reads --sample-names $f; done
```

**Comment by Xinzhao1990** [comment]
Hi David

The code is working! Thank you very much!

**Comment by dcdanko** [comment]
:)
